#!/usr/bin/env node
/**
 * UI Creator MCP Server
 *
 * Enables anyone with Claude Code to build full SaaS apps through chat.
 * Supports multiple apps — each gets its own isolated namespace in KV
 * and its own Cloudflare Worker deployment.
 *
 * Install: git clone https://github.com/vgpprasad91/ui-creator-mcp.git
 * Configure: Add to ~/.claude.json under mcpServers
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ListResourcesRequestSchema,
  ReadResourceRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { readFileSync, existsSync, writeFileSync, mkdirSync } from "fs";
import { resolve, join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Load the catalog prompt generated by json-render
const catalogPromptPath = resolve(__dirname, "../catalog-prompt.txt");
const CATALOG_PROMPT = existsSync(catalogPromptPath)
  ? readFileSync(catalogPromptPath, "utf-8")
  : "Generate a json-render spec with { root, elements } format.";

// ─── Config ──────────────────────────────────────────────────────

interface ServerConfig {
  accountId?: string;
  apiToken?: string;
  kvNamespaceId?: string;
  appId: string;
  runtimeUrl?: string;
  localDir?: string;
}

// Mutable — changes when switching apps
let config: ServerConfig = {
  accountId: process.env.CF_ACCOUNT_ID || process.env.CLOUDFLARE_ACCOUNT_ID,
  apiToken: process.env.CF_API_TOKEN || process.env.CLOUDFLARE_API_TOKEN,
  kvNamespaceId: process.env.CF_KV_NAMESPACE_ID,
  appId: process.env.UI_CREATOR_APP_ID || "my-app",
  runtimeUrl: process.env.UI_CREATOR_RUNTIME_URL,
  localDir: process.env.UI_CREATOR_LOCAL_DIR || "./ui-creator-app",
};

// Track the app registry in memory (loaded from KV on first use)
let appRegistryCache: Record<string, { name: string; runtimeUrl?: string; createdAt: string }> | null = null;

// ─── Component Manifest ──────────────────────────────────────────

function loadManifest(): Record<string, unknown> {
  const bundledPath = resolve(__dirname, "../manifest/components.schema.json");
  if (existsSync(bundledPath)) {
    return JSON.parse(readFileSync(bundledPath, "utf-8"));
  }
  return { error: "Component manifest not found." };
}

// ─── KV Client ───────────────────────────────────────────────────

async function kvPut(key: string, value: string): Promise<void> {
  if (!config.accountId || !config.apiToken || !config.kvNamespaceId) {
    throw new Error("Missing Cloudflare credentials. Set CF_ACCOUNT_ID, CF_API_TOKEN, and CF_KV_NAMESPACE_ID.");
  }
  const url = `https://api.cloudflare.com/client/v4/accounts/${config.accountId}/storage/kv/namespaces/${config.kvNamespaceId}/values/${encodeURIComponent(key)}`;
  const res = await fetch(url, {
    method: "PUT",
    headers: { Authorization: `Bearer ${config.apiToken}`, "Content-Type": "text/plain" },
    body: value,
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`KV PUT failed (${res.status}): ${body}`);
  }
}

async function kvGet(key: string): Promise<string | null> {
  if (!config.accountId || !config.apiToken || !config.kvNamespaceId) return null;
  const url = `https://api.cloudflare.com/client/v4/accounts/${config.accountId}/storage/kv/namespaces/${config.kvNamespaceId}/values/${encodeURIComponent(key)}`;
  const res = await fetch(url, { headers: { Authorization: `Bearer ${config.apiToken}` } });
  if (res.status === 404 || !res.ok) return null;
  return res.text();
}

async function kvList(prefix: string): Promise<string[]> {
  if (!config.accountId || !config.apiToken || !config.kvNamespaceId) return [];
  const url = `https://api.cloudflare.com/client/v4/accounts/${config.accountId}/storage/kv/namespaces/${config.kvNamespaceId}/keys?prefix=${encodeURIComponent(prefix)}&limit=1000`;
  const res = await fetch(url, { headers: { Authorization: `Bearer ${config.apiToken}` } });
  if (!res.ok) return [];
  const data = await res.json() as any;
  return (data.result || []).map((k: any) => k.name);
}

// ─── App Registry ────────────────────────────────────────────────

const REGISTRY_KEY = "__ui_creator_apps__";

async function loadAppRegistry(): Promise<Record<string, { name: string; runtimeUrl?: string; createdAt: string }>> {
  if (appRegistryCache) return appRegistryCache;
  const raw = await kvGet(REGISTRY_KEY);
  appRegistryCache = raw ? JSON.parse(raw) : {};
  return appRegistryCache!;
}

async function saveAppRegistry(registry: Record<string, { name: string; runtimeUrl?: string; createdAt: string }>): Promise<void> {
  appRegistryCache = registry;
  await kvPut(REGISTRY_KEY, JSON.stringify(registry));
}

// ─── Validation ──────────────────────────────────────────────────

interface ValidationResult {
  errors: string[];
  warnings: string[];
}

// All component types from COMPONENT_MAP in ConfigRenderer.tsx
const COMPONENT_MAP_TYPES = new Set([
  // Cards
  "Card", "card", "CardHeader", "CardTitle", "CardDescription", "CardContent", "CardFooter",
  // Buttons & Actions
  "Button", "button", "OAuthButton", "oauth_button",
  // Display
  "Badge", "badge", "Separator", "separator", "Avatar", "avatar", "Skeleton", "skeleton", "Icon", "icon",
  // Forms & Inputs
  "Form", "form", "Input", "input", "Textarea", "textarea", "Label", "label_component",
  "Select", "select_component", "Checkbox", "checkbox", "Switch", "switch_component",
  "RadioGroup", "radio_group", "Slider", "slider",
  // Layout
  "Grid", "grid", "ScrollArea", "scroll_area", "AspectRatio", "aspect_ratio",
  "ResizablePanelGroup", "resizable_panel_group", "ResizablePanel", "resizable_panel",
  "ResizableHandle", "resizable_handle", "Collapsible", "collapsible",
  // Overlays & Modals
  "Dialog", "dialog", "DialogHeader", "DialogFooter", "DialogTitle", "DialogDescription",
  "Sheet", "sheet", "SheetHeader", "SheetFooter", "SheetTitle", "SheetDescription",
  "AlertDialog", "alert_dialog", "Drawer", "drawer",
  "Popover", "popover", "HoverCard", "hover_card", "Tooltip", "tooltip",
  "DropdownMenu", "dropdown_menu", "ContextMenu", "context_menu",
  // Feedback
  "Alert", "alert", "AlertTitle", "AlertDescription", "Progress", "progress", "Toaster", "toaster",
  // Navigation
  "Breadcrumb", "breadcrumb", "Pagination", "pagination",
  "NavigationMenu", "navigation_menu", "Menubar", "menubar",
  // Data Display
  "Table", "table_component", "TableHeader", "TableBody", "TableFooter", "TableRow",
  "TableHead", "TableCell", "TableCaption",
  "Accordion", "accordion", "Calendar", "calendar", "Carousel", "carousel", "Command", "command",
  // Tabs
  "Tabs", "tabs", "ShadcnTabs", "shadcn_tabs", "TabsList", "TabsTrigger", "TabsContent",
  // Toggle
  "Toggle", "toggle", "ToggleGroup", "toggle_group",
  // Dashboard Primitives
  "PageHeader", "page_header", "StatCard", "stat_card", "DataTable", "data_table",
  "ActivityFeed", "activity_feed",
  // Special
  "Link",
]);

// Plugin components (loaded dynamically, also valid)
const PLUGIN_COMPONENTS = new Set([
  // Charts
  "BarChart", "LineChart", "AreaChart", "DonutChart", "PieChart", "SparkChart", "BarList", "CategoryBar", "Tracker",
  // AI
  "ChatMessage", "ChatInput", "StreamingText", "MarkdownPreview", "CodeBlock", "FeedbackButtons", "SourceCitation",
  // Advanced
  "DatePicker", "DateRangePicker", "MultiSelect", "FileUpload", "Stepper", "Timeline",
  "Kanban", "VirtualDataGrid", "RichTextEditor", "ColorPicker", "CommandPalette", "DiffViewer",
  // Magic
  "Marquee", "BlurFade", "AnimatedBeam", "GradientText", "TypingAnimation", "NumberTicker",
  "ParticleField", "DockNav",
  // Media
  "AudioRecorder", "AudioPlayer", "VideoPlayer", "VideoRecorder", "ImageAnnotator", "ScreenCapture",
]);

function isKnownComponent(type: string): boolean {
  return COMPONENT_MAP_TYPES.has(type) || PLUGIN_COMPONENTS.has(type) || HTML_ELEMENTS.has(type);
}

// json-render native spec types — these are the component types supported by the Renderer
const JSON_RENDER_SPEC_TYPES = new Set([
  // shadcn 36 core types
  "Card", "Stack", "Grid", "Separator", "Tabs", "Accordion", "Collapsible",
  "Dialog", "Drawer", "Carousel", "Table", "Heading", "Text", "Image",
  "Avatar", "Badge", "Alert", "Progress", "Skeleton", "Spinner",
  "Tooltip", "Popover", "Input", "Textarea", "Select", "Checkbox",
  "Radio", "Switch", "Slider", "Button", "Link", "DropdownMenu",
  "Toggle", "ToggleGroup", "ButtonGroup", "Pagination",
  // Custom types
  "StatCard", "PageHeader", "DataTable", "ActivityFeed", "Icon",
  "Navbar", "SideNav", "LineChart", "AIAssistant",
  // Fallback types — render as placeholder cards, not invisible
  "Kanban", "Calendar", "Timeline", "FileUpload", "RichTextEditor",
  "ColorPicker", "DatePicker",
]);

// Suggestions for common unknown types → closest catalog equivalent
const TYPE_SUGGESTIONS: Record<string, string> = {
  "List": "Stack (with children)",
  "Section": "Card",
  "Container": "Stack or Card",
  "Box": "Stack or Card",
  "Flex": "Stack (direction: horizontal/vertical)",
  "Row": "Stack (direction: horizontal)",
  "Column": "Stack (direction: vertical)",
  "Header": "PageHeader or Heading",
  "Footer": "Stack with Text",
  "Sidebar": "Stack inside Grid",
  "Nav": "Stack with Link children",
  "Form": "Stack with Input/Select/Checkbox children",
  "Chart": "Card with Text (charts require plugin)",
  "BarChart": "Card (charts require plugin)",
  "LineChart": "Card (charts require plugin)",
  "PieChart": "Card (charts require plugin)",
  "Divider": "Separator",
  "Hr": "Separator",
  "Label": "Text",
  "Paragraph": "Text",
  "H1": "Heading (level: 1)",
  "H2": "Heading (level: 2)",
  "H3": "Heading (level: 3)",
  "Img": "Image",
  "Tag": "Badge",
  "Chip": "Badge",
  "Modal": "Dialog",
  "Sheet": "Drawer",
};

function validateNativeSpec(spec: any): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!spec || typeof spec !== "object") {
    errors.push("spec must be an object");
    return { errors, warnings };
  }

  if (typeof spec.root !== "string") {
    errors.push('spec.root must be a string (the ID of the root element)');
    return { errors, warnings };
  }

  if (!spec.elements || typeof spec.elements !== "object") {
    errors.push('spec.elements must be an object mapping element IDs to definitions');
    return { errors, warnings };
  }

  // Check root exists in elements
  if (!spec.elements[spec.root]) {
    errors.push(`spec.root "${spec.root}" does not exist in spec.elements`);
  }

  // Validate each element
  for (const [id, el] of Object.entries(spec.elements)) {
    const elem = el as any;
    const path = `elements.${id}`;

    if (!elem || typeof elem !== "object") {
      errors.push(`${path}: element must be an object`);
      continue;
    }

    // type is required and must be a string
    if (typeof elem.type !== "string") {
      errors.push(`${path}: "type" must be a string`);
    } else if (!JSON_RENDER_SPEC_TYPES.has(elem.type)) {
      const suggestion = TYPE_SUGGESTIONS[elem.type];
      const hint = suggestion ? ` Try: ${suggestion}` : ` Available types: Card, Stack, Grid, Heading, Text, Badge, Button, Tabs, Table, StatCard, DataTable, PageHeader, etc.`;
      errors.push(`${path}: Unknown component type "${elem.type}" — not in the catalog and will not render.${hint}`);
    }

    // props must be an object
    if (elem.props !== undefined && (typeof elem.props !== "object" || Array.isArray(elem.props))) {
      errors.push(`${path}: "props" must be an object`);
    }

    // children must be an array of strings
    if (!Array.isArray(elem.children)) {
      errors.push(`${path}: "children" must be an array of element ID strings`);
    } else {
      for (let ci = 0; ci < elem.children.length; ci++) {
        const childId = elem.children[ci];
        if (typeof childId !== "string") {
          errors.push(`${path}.children[${ci}]: child must be a string ID, got ${typeof childId}`);
        } else if (!spec.elements[childId]) {
          errors.push(`${path}.children[${ci}]: child ID "${childId}" does not exist in spec.elements`);
        }
      }
    }
  }

  return { errors, warnings };
}

function validatePageConfig(pageConfig: unknown): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  if (!pageConfig || typeof pageConfig !== "object") {
    errors.push("Config must be a JSON object");
    return { errors, warnings };
  }
  const c = pageConfig as Record<string, unknown>;
  if (!c.page && !c.template) {
    errors.push('Config must have a "page" object or a "template" reference');
  }
  if (c.page && typeof c.page === "object") {
    const page = c.page as Record<string, unknown>;
    if (!page.title) errors.push("page.title is required");

    // ── Native json-render spec format ──
    if (page.spec && typeof page.spec === "object") {
      const specResult = validateNativeSpec(page.spec);
      errors.push(...specResult.errors);
      warnings.push(...specResult.warnings);
      return { errors, warnings };
    }

    // ── Legacy tree format ──
    if (!page.body && !page.aside) errors.push("page.body or page.aside is required (or use page.spec for native json-render format)");
    if (Array.isArray(page.body)) {
      const manifest = loadManifest();
      const knownComponents = new Set<string>();
      if (Array.isArray((manifest as any).components)) {
        for (const comp of (manifest as any).components) {
          knownComponents.add(comp.name);
          if (comp.aliases) comp.aliases.forEach((a: string) => knownComponents.add(a));
        }
      }
      const checkNodes = (nodes: unknown[], path: string = "body") => {
        for (let i = 0; i < nodes.length; i++) {
          const node = nodes[i];
          if (node && typeof node === "object") {
            const n = node as Record<string, unknown>;
            const type = (n.type ?? n.component) as string | undefined;
            const nodePath = `${path}[${i}]`;

            if (typeof type === "string") {
              // Check if component is known at all
              if (!isKnownComponent(type) && knownComponents.size > 0 && !knownComponents.has(type)) {
                warnings.push(`${nodePath}: Unknown component type "${type}" — will render as a generic div.`);
              }

              const props = (n.props || {}) as Record<string, unknown>;

              // ── Structural prop validation ──

              // Tabs: must have props.tabs as array with value, label, and children (not content)
              if (type === "Tabs" || type === "tabs") {
                if (!props.tabs || !Array.isArray(props.tabs)) {
                  errors.push(`${nodePath}: Tabs MUST have props.tabs as an array.`);
                } else {
                  for (let ti = 0; ti < (props.tabs as any[]).length; ti++) {
                    const tab = (props.tabs as any[])[ti];
                    if (!tab.value || typeof tab.value !== "string") {
                      errors.push(`${nodePath}.tabs[${ti}]: Each tab MUST have a "value" string.`);
                    }
                    if (!tab.label || typeof tab.label !== "string") {
                      errors.push(`${nodePath}.tabs[${ti}]: Each tab MUST have a "label" string.`);
                    }
                    if (tab.content && !tab.children) {
                      errors.push(`${nodePath}.tabs[${ti}]: Tab body must be in "children", NOT "content". Rename "content" to "children".`);
                    }
                    // Recurse into tab children
                    if (Array.isArray(tab.children)) {
                      checkNodes(tab.children, `${nodePath}.tabs[${ti}].children`);
                    }
                  }
                }
              }

              // Grid: cols should be number or breakpoint object, gap should be number
              if (type === "Grid" || type === "grid") {
                if (props.cols !== undefined) {
                  if (typeof props.cols === "string") {
                    errors.push(`${nodePath}: Grid props.cols must be a number or breakpoint object {default, sm, md, lg, xl}, NOT a string.`);
                  }
                }
                if (props.gap !== undefined && typeof props.gap !== "number") {
                  warnings.push(`${nodePath}: Grid props.gap should be a number (e.g., 4). Got ${typeof props.gap}.`);
                }
              }

              // StatCard: must have title/label and value
              if (type === "StatCard" || type === "stat_card") {
                if (!props.title && !props.label) {
                  errors.push(`${nodePath}: StatCard MUST have props.title or props.label.`);
                }
                if (props.value === undefined && props.value !== 0) {
                  errors.push(`${nodePath}: StatCard MUST have props.value.`);
                }
              }

              // DataTable: must have columns array with key and label
              if (type === "DataTable" || type === "data_table") {
                if (!props.columns || !Array.isArray(props.columns)) {
                  errors.push(`${nodePath}: DataTable MUST have props.columns as an array.`);
                } else {
                  for (let ci = 0; ci < (props.columns as any[]).length; ci++) {
                    const col = (props.columns as any[])[ci];
                    if (!col.key) {
                      errors.push(`${nodePath}.columns[${ci}]: Each column MUST have a "key".`);
                    }
                    if (!col.label) {
                      errors.push(`${nodePath}.columns[${ci}]: Each column MUST have a "label".`);
                    }
                  }
                }
              }

              // Card: title should be in props, not as a child text node
              if (type === "Card" || type === "card") {
                if (props.title !== undefined && typeof props.title !== "string") {
                  warnings.push(`${nodePath}: Card props.title should be a string.`);
                }
              }

              // PageHeader: should have props.title as string
              if (type === "PageHeader" || type === "page_header") {
                if (!props.title || typeof props.title !== "string") {
                  warnings.push(`${nodePath}: PageHeader should have props.title as a string.`);
                }
              }

              // Badge: should have text or children
              if (type === "Badge" || type === "badge") {
                if (!n.text && !n.children && !props.text) {
                  warnings.push(`${nodePath}: Badge should have "text" or "children" to display content.`);
                }
              }

              // Button: should have text or children
              if (type === "Button" || type === "button") {
                if (!n.text && !n.children && !props.text) {
                  warnings.push(`${nodePath}: Button should have "text" or "children" to display content.`);
                }
              }

              // Form: should have schema prop
              if (type === "Form" || type === "form") {
                if (!props.schema) {
                  warnings.push(`${nodePath}: Form should have a "schema" prop referencing a form definition.`);
                }
              }

              // Icon: must have props.name
              if (type === "Icon" || type === "icon") {
                if (!props.name || typeof props.name !== "string") {
                  errors.push(`${nodePath}: Icon MUST have props.name as a string.`);
                }
              }

              // Detect raw div used as layout container (should be Grid)
              if (type === "div" && Array.isArray(n.children) && (n.children as unknown[]).length >= 3) {
                const kids = n.children as any[];
                const allCards = kids.every((k: any) => k && typeof k === "object" && (k.type === "Card" || k.type === "card" || k.type === "StatCard" || k.type === "stat_card" || k.type === "div"));
                if (allCards && kids.length >= 3) {
                  errors.push(`${nodePath}: Use "Grid" instead of "div" for multi-item layouts (${kids.length} children). Raw divs stack vertically. Change type to "Grid" and add props.cols.`);
                }
              }
            }

            // Recurse into children and body
            if (Array.isArray(n.children)) checkNodes(n.children as unknown[], `${nodePath}.children`);
            if (Array.isArray(n.body)) checkNodes(n.body as unknown[], `${nodePath}.body`);
          }
        }
      };
      checkNodes(page.body as unknown[]);
    }
  }
  return { errors, warnings };
}

const HTML_ELEMENTS = new Set([
  "div", "span", "p", "h1", "h2", "h3", "h4", "h5", "h6", "a", "ul", "ol", "li",
  "img", "pre", "code", "section", "article", "header", "footer", "nav", "main",
  "table", "thead", "tbody", "tr", "th", "td", "form", "input", "button", "label",
  "select", "textarea", "blockquote", "hr", "br",
]);
function isHtmlElement(type: string): boolean { return HTML_ELEMENTS.has(type); }

// ─── Wrangler Deploy Helper ──────────────────────────────────────

function generateWranglerToml(appId: string): string {
  // Full wrangler config with ALL bindings the runtime requires.
  // Uses shared infrastructure — all apps share the same D1, R2, KV, DO, Queues.
  // Only name and APP_ID differ per app.
  return `name = "${appId}"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[vars]
APP_ID = "${appId}"
APP_ENV = "production"

# ─── KV Namespaces (shared) ───
[[kv_namespaces]]
binding = "CF_KV_SESSIONS"
id = "f06f2c34dfa3483c9ac12f5b60def097"

[[kv_namespaces]]
binding = "CF_KV_CONFIG"
id = "687f7f470c7349578fbde50079ec3196"

[[kv_namespaces]]
binding = "CF_KV_CACHE"
id = "c3604887d443439fa201227848c356b8"

[[kv_namespaces]]
binding = "CF_KV_CLIENTFORCE_CONFIG"
id = "afd09645d27643279f4cc88a6a82af58"

[[kv_namespaces]]
binding = "CF_KV_SHARED_CONFIG"
id = "88ea4e1fbe304e29a359bfd29b5ca618"

# ─── D1 Databases (shared) ───
[[d1_databases]]
binding = "CF_D1_PRIMARY"
database_name = "d1-primary"
database_id = "95276a82-fb36-4ea1-adf2-233e6930f950"

[[d1_databases]]
binding = "CF_D1_CLIENTFORCE"
database_name = "cf-d1-clientforce"
database_id = "c95fee25-eaa7-4e5f-a9fe-685fe60512b6"

[[d1_databases]]
binding = "CF_D1_SHARED_POOL"
database_name = "cf-d1-shared-pool"
database_id = "841fc7e5-bf49-4240-a2d4-3de109a80765"

# ─── R2 Buckets (shared) ───
[[r2_buckets]]
binding = "CF_R2_UPLOADS"
bucket_name = "r2-uploads"

[[r2_buckets]]
binding = "CF_R2_EXPORTS"
bucket_name = "r2-exports"

[[r2_buckets]]
binding = "CF_R2_CLIENTFORCE_UPLOADS"
bucket_name = "cf-r2-clientforce-uploads"

[[r2_buckets]]
binding = "CF_R2_SHARED_UPLOADS"
bucket_name = "cf-r2-shared-uploads"

# ─── Durable Objects ───
[durable_objects]
bindings = [
  { name = "CF_DO_PRESENCE", class_name = "PresenceDO" },
  { name = "CF_DO_RATELIMIT", class_name = "RateLimitDO" },
]

[[migrations]]
tag = "v1"
new_classes = ["PresenceDO", "RateLimitDO"]

# ─── Queues (producers only) ───
[[queues.producers]]
binding = "CF_QUEUE_NOTIFICATIONS"
queue = "queue-notifications"

[[queues.producers]]
binding = "CF_QUEUE_CLIENTFORCE_NOTIFICATIONS"
queue = "cf-queue-clientforce-notifications"

[[queues.producers]]
binding = "CF_QUEUE_SHARED_NOTIFICATIONS"
queue = "cf-queue-shared-notifications"

# ─── AI ───
[ai]
binding = "AI"

# ─── Analytics Engine ───
[[analytics_engine_datasets]]
binding = "CF_ANALYTICS_ENGINE"

# ─── Workflows ───
[[workflows]]
binding = "CF_WORKFLOW_INVOICE"
name = "invoice"
class_name = "InvoiceLifecycleWorkflow"

[[workflows]]
binding = "CF_WORKFLOW_ONBOARDING"
name = "onboarding"
class_name = "ClientOnboardingWorkflow"

[[workflows]]
binding = "CF_WORKFLOW_INVITE"
name = "invite"
class_name = "TeamInviteWorkflow"

[[workflows]]
binding = "CF_WORKFLOW_ERASURE"
name = "erasure"
class_name = "DataErasureWorkflow"
`;
}

// ─── MCP Server ──────────────────────────────────────────────────

const server = new Server(
  { name: "ui-creator", version: "2.0.0" },
  { capabilities: { tools: {}, resources: {} } },
);

// ─── Resources ───────────────────────────────────────────────────

server.setRequestHandler(ListResourcesRequestSchema, async () => ({
  resources: [{
    uri: "ui-creator://manifest/components.schema.json",
    name: "Component Manifest",
    description: "Registry of 99 components, props, plugins, and 16 page templates.",
    mimeType: "application/json",
  }],
}));

server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
  if (request.params.uri === "ui-creator://manifest/components.schema.json") {
    const manifest = loadManifest();
    return { contents: [{ uri: request.params.uri, mimeType: "application/json", text: JSON.stringify(manifest, null, 2) }] };
  }
  throw new Error(`Unknown resource: ${request.params.uri}`);
});

// ─── Tools ───────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    // ── App Management ──
    {
      name: "create_app",
      description:
        "Create a new app with its own isolated namespace. Each app gets separate configs in KV and can be deployed as its own Worker. " +
        "ALWAYS call this first when the user wants to build a new app. This sets the active app context so all subsequent publish calls go to the right place.",
      inputSchema: {
        type: "object" as const,
        properties: {
          appId: { type: "string", description: 'Unique app identifier, lowercase with hyphens (e.g., "spice-garden", "invoice-tracker", "gym-scheduler")' },
          name: { type: "string", description: 'Human-readable app name (e.g., "Your Spice Garden", "Invoice Tracker")' },
          description: { type: "string", description: "Short description of the app" },
          public: { type: "boolean", description: "If true, all pages default to public (no auth). Default: true for new apps." },
        },
        required: ["appId", "name"],
      },
    },
    {
      name: "list_apps",
      description: "List all apps that have been created. Shows app IDs, names, and which configs are published.",
      inputSchema: { type: "object" as const, properties: {} },
    },
    {
      name: "switch_app",
      description: "Switch the active app context. All subsequent publish/read calls will target this app's namespace.",
      inputSchema: {
        type: "object" as const,
        properties: {
          appId: { type: "string", description: "The app ID to switch to" },
        },
        required: ["appId"],
      },
    },
    {
      name: "deploy_app",
      description:
        "Deploy the current app as a new Cloudflare Worker. Creates a Worker with the app's APP_ID, sharing the same KV namespace. " +
        "After deployment, the app is live at https://{appId}.{subdomain}.workers.dev",
      inputSchema: {
        type: "object" as const,
        properties: {
          appId: { type: "string", description: "App ID to deploy (defaults to current active app)" },
        },
      },
    },
    // ── Component Discovery ──
    {
      name: "get_component_manifest",
      description:
        "Get the component manifest. Without a category, returns a compact index. " +
        "With a category, returns full details including all props. Call this first to see what's available.",
      inputSchema: {
        type: "object" as const,
        properties: {
          category: { type: "string", description: 'Filter: "layout", "data", "forms", "charts", "ai", "magic", "advanced", "media"' },
          component: { type: "string", description: 'Single component by name (e.g., "stat_card", "BarChart")' },
        },
      },
    },
    {
      name: "get_templates",
      description: "List available page templates. Use as starting points for pages.",
      inputSchema: {
        type: "object" as const,
        properties: {
          category: { type: "string", description: "Filter by category" },
        },
      },
    },
    // ── Validation ──
    {
      name: "validate_page_config",
      description: "Validate a page config JSON before publishing.",
      inputSchema: {
        type: "object" as const,
        properties: { config: { type: "object", description: "The page config JSON" } },
        required: ["config"],
      },
    },
    // ── Publishing ──
    {
      name: "save_page_config",
      description: "Save a page config to local directory for preview.",
      inputSchema: {
        type: "object" as const,
        properties: {
          pageName: { type: "string", description: 'Page name (e.g., "dashboard")' },
          config: { type: "object", description: "The page config JSON" },
        },
        required: ["pageName", "config"],
      },
    },
    {
      name: "publish_page_config",
      description:
        "Publish a page config to KV. The config MUST contain a 'spec' field in json-render native format.\n\n" +
        "IMPORTANT: Follow these rules for generating the spec:\n\n" +
        CATALOG_PROMPT.slice(0, 8000),
      inputSchema: {
        type: "object" as const,
        properties: {
          pageName: { type: "string", description: 'Page name (e.g., "pages/dashboard")' },
          config: { type: "object", description: "Page config with { page: { title, layout, spec: { root, elements } } }" },
          path: { type: "string", description: 'URL path (e.g., "/dashboard")' },
          public: { type: "boolean", description: "If true, no auth required" },
        },
        required: ["pageName", "config"],
      },
    },
    {
      name: "publish_manifest",
      description: "Publish the full app manifest to KV. Defines routes, loading strategies.",
      inputSchema: {
        type: "object" as const,
        properties: { manifest: { type: "object", description: "The manifest.json config" } },
        required: ["manifest"],
      },
    },
    {
      name: "publish_theme",
      description: "Publish a theme config. Controls colors, fonts, radius.",
      inputSchema: {
        type: "object" as const,
        properties: { theme: { type: "object", description: "Theme config with HSL colors, fonts, radius" } },
        required: ["theme"],
      },
    },
    {
      name: "publish_datasources",
      description: "Publish datasource definitions.",
      inputSchema: {
        type: "object" as const,
        properties: { datasources: { type: "object", description: "Datasources config" } },
        required: ["datasources"],
      },
    },
    {
      name: "publish_navigation",
      description: "Publish sidebar navigation config.",
      inputSchema: {
        type: "object" as const,
        properties: { navigation: { type: "object", description: "Navigation config" } },
        required: ["navigation"],
      },
    },
    {
      name: "get_app_status",
      description: "Check current app status — active app ID, published configs, runtime URL.",
      inputSchema: { type: "object" as const, properties: {} },
    },
    {
      name: "get_ui_schema",
      description: "Get the complete UI component schema and generation rules. Call this BEFORE creating any page config to understand what components are available and how to structure the spec.",
      inputSchema: { type: "object" as const, properties: {} },
    },
  ],
}));

// ─── Tool Handlers ───────────────────────────────────────────────

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name: toolName, arguments: args } = request.params;

  switch (toolName) {

    // ════════════════════════════════════════════════════
    // APP MANAGEMENT
    // ════════════════════════════════════════════════════

    case "create_app": {
      const { appId, name: appName, description: appDesc, public: isPublic } = args as any;

      // Validate app ID
      if (!/^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(appId) || appId.length < 3) {
        return { content: [{ type: "text", text: `Invalid app ID "${appId}". Must be lowercase, hyphens only, at least 3 chars (e.g., "spice-garden").` }] };
      }

      // Switch active context to new app
      config.appId = appId;

      // Create initial manifest with base routes
      const defaultPublic = isPublic !== false; // default true for new apps
      const manifest = {
        $schema: "ui-creator-manifest/v1",
        $version: 1,
        app: appId,  // MUST be a string — runtime uses manifest.app as the KV key prefix
        load: {
          eager: [
            { file: "theme", ttl: 3600, priority: 1 },
            { file: "navigation", ttl: 3600, priority: 2 },
          ] as any[],
          lazy: [] as any[],
          routes: [] as any[]
        },
        merge_strategy: {},
      };

      await kvPut(`config:${appId}:manifest`, JSON.stringify(manifest));

      // Register in app registry
      const registry = await loadAppRegistry();
      registry[appId] = {
        name: appName,
        runtimeUrl: config.runtimeUrl ? config.runtimeUrl.replace(/clientforce-portal|[^/]+(?=\.vguruprasad91)/, appId) : undefined,
        createdAt: new Date().toISOString(),
      };
      await saveAppRegistry(registry);

      const runtimeNote = config.runtimeUrl
        ? `\nRuntime: The app will be live at https://${appId}.vguruprasad91.workers.dev once deployed.`
        : "";

      return { content: [{ type: "text", text:
        `App "${appName}" created (ID: ${appId}).\n` +
        `Active app switched to: ${appId}\n` +
        `Default page visibility: ${defaultPublic ? "public" : "authenticated"}\n` +
        `KV namespace: config:${appId}:*${runtimeNote}\n\n` +
        `Next steps:\n` +
        `1. publish_theme — set colors and fonts\n` +
        `2. publish_navigation — set sidebar menu\n` +
        `3. publish_page_config — create pages (routes added automatically)\n` +
        `4. deploy_app — deploy as a Cloudflare Worker`
      }] };
    }

    case "list_apps": {
      const registry = await loadAppRegistry();
      const appIds = Object.keys(registry);

      if (appIds.length === 0) {
        // Check KV for any config keys to find apps
        const keys = await kvList("config:");
        const discovered = new Set<string>();
        for (const key of keys) {
          const match = key.match(/^config:([^:]+):/);
          if (match) discovered.add(match[1]);
        }

        if (discovered.size === 0) {
          return { content: [{ type: "text", text: "No apps found. Use create_app to create your first app." }] };
        }

        return { content: [{ type: "text", text: JSON.stringify({
          active: config.appId,
          apps: Array.from(discovered).map(id => ({
            id,
            active: id === config.appId,
            note: "Discovered from KV keys (no registry entry)",
          })),
        }, null, 2) }] };
      }

      const apps = await Promise.all(appIds.map(async (id) => {
        const info = registry[id];
        const hasManifest = (await kvGet(`config:${id}:manifest`)) !== null;
        const hasTheme = (await kvGet(`config:${id}:theme`)) !== null;
        const pageKeys = await kvList(`config:${id}:pages/`);
        return {
          id,
          name: info.name,
          active: id === config.appId,
          runtimeUrl: info.runtimeUrl,
          createdAt: info.createdAt,
          configs: { manifest: hasManifest, theme: hasTheme, pages: pageKeys.length },
        };
      }));

      return { content: [{ type: "text", text: JSON.stringify({ active: config.appId, apps }, null, 2) }] };
    }

    case "switch_app": {
      const { appId } = args as any;
      const oldId = config.appId;
      config.appId = appId;

      // Check if this app exists in KV
      const hasManifest = (await kvGet(`config:${appId}:manifest`)) !== null;
      const pageKeys = await kvList(`config:${appId}:pages/`);

      return { content: [{ type: "text", text:
        `Switched from "${oldId}" to "${appId}".\n` +
        `Manifest: ${hasManifest ? "exists" : "not found"}\n` +
        `Pages: ${pageKeys.length} published\n` +
        `All publish calls now target: config:${appId}:*`
      }] };
    }

    case "deploy_app": {
      const appId = (args as any)?.appId || config.appId;
      const toml = generateWranglerToml(appId);

      // Save wrangler.toml locally for reference
      const deployDir = resolve(config.localDir || "./ui-creator-app", appId);
      mkdirSync(deployDir, { recursive: true });
      writeFileSync(join(deployDir, "wrangler.toml"), toml);

      // For actual deployment, we need the runtime source + public assets
      // The user's runtime is already built — we just need to deploy with a different name
      const runtimeDir = resolve(__dirname, "../../runtime");
      const hasRuntime = existsSync(join(runtimeDir, "src/index.ts"));

      if (!hasRuntime) {
        return { content: [{ type: "text", text:
          `Generated wrangler.toml for "${appId}" at ${join(deployDir, "wrangler.toml")}.\n\n` +
          `To deploy manually:\n` +
          `1. Copy this wrangler.toml to the runtime directory\n` +
          `2. Run: npx wrangler deploy\n` +
          `3. The app will be live at https://${appId}.vguruprasad91.workers.dev\n\n` +
          `Note: All apps share the same KV namespace, so configs are already published. ` +
          `The Worker just needs the right APP_ID env var to read the correct configs.`
        }] };
      }

      return { content: [{ type: "text", text:
        `Ready to deploy "${appId}".\n\n` +
        `Wrangler config saved to: ${join(deployDir, "wrangler.toml")}\n` +
        `Runtime found at: ${runtimeDir}\n\n` +
        `To deploy, run in terminal:\n` +
        `  cd ${runtimeDir}\n` +
        `  cp ${join(deployDir, "wrangler.toml")} wrangler-${appId}.toml\n` +
        `  npx wrangler deploy -c wrangler-${appId}.toml\n\n` +
        `After deploy: https://${appId}.vguruprasad91.workers.dev\n` +
        `All configs are already in KV under config:${appId}:*`
      }] };
    }

    // ════════════════════════════════════════════════════
    // COMPONENT DISCOVERY
    // ════════════════════════════════════════════════════

    case "get_component_manifest": {
      const manifest = loadManifest();
      const components: any[] = (manifest as any).components || [];
      const templates: any[] = (manifest as any).templates || [];

      if ((args as any)?.component) {
        const cName = (args as any).component;
        const comp = components.find((c: any) => c.name === cName || (c.aliases?.includes(cName)));
        if (comp) return { content: [{ type: "text", text: JSON.stringify(comp, null, 2) }] };
        return { content: [{ type: "text", text: `Component "${cName}" not found.` }] };
      }

      if ((args as any)?.category) {
        const cat = (args as any).category;
        const filtered = components.filter((c: any) => c.category === cat || c.plugin === cat);
        return { content: [{ type: "text", text: JSON.stringify({ components: filtered, total: filtered.length }, null, 2) }] };
      }

      const grouped: Record<string, string[]> = {};
      for (const c of components) {
        const key = c.plugin && c.plugin !== "core" ? c.plugin : (c.category || "core");
        if (!grouped[key]) grouped[key] = [];
        grouped[key].push(c.name);
      }

      return { content: [{ type: "text", text: JSON.stringify({
        total_components: components.length,
        total_templates: templates.length,
        active_app: config.appId,
        categories: grouped,
        templates: templates.map((t: any) => ({ name: t.name, category: t.category })),
        usage: "Call with category or component for full props.",
      }, null, 2) }] };
    }

    case "get_templates": {
      const manifest = loadManifest();
      let templates = (manifest as any).templates || [];
      if ((args as any)?.category) {
        templates = templates.filter((t: any) => t.category === (args as any).category);
      }
      return { content: [{ type: "text", text: JSON.stringify({ templates, total: templates.length }, null, 2) }] };
    }

    // ════════════════════════════════════════════════════
    // VALIDATION
    // ════════════════════════════════════════════════════

    case "validate_page_config": {
      const { errors, warnings } = validatePageConfig((args as any).config);
      const parts: string[] = [];
      if (errors.length > 0) {
        parts.push(`Errors (must fix before publishing):\n${errors.map(e => `  - ${e}`).join("\n")}`);
      }
      if (warnings.length > 0) {
        parts.push(`Warnings:\n${warnings.map(w => `  - ${w}`).join("\n")}`);
      }
      if (errors.length === 0 && warnings.length === 0) {
        return { content: [{ type: "text", text: "Config is valid. Ready to publish." }] };
      }
      if (errors.length === 0) {
        return { content: [{ type: "text", text: `Config is valid with warnings. Ready to publish.\n\n${parts.join("\n\n")}` }] };
      }
      return { content: [{ type: "text", text: parts.join("\n\n") }] };
    }

    // ════════════════════════════════════════════════════
    // PUBLISHING
    // ════════════════════════════════════════════════════

    case "save_page_config": {
      const { pageName, config: pageConfig } = args as any;
      const dir = resolve(config.localDir || "./ui-creator-app", config.appId);
      const filePath = join(dir, "pages", `${pageName}.json`);
      mkdirSync(dirname(filePath), { recursive: true });
      writeFileSync(filePath, JSON.stringify(pageConfig, null, 2));
      return { content: [{ type: "text", text: `Saved to ${filePath}` }] };
    }

    case "publish_page_config": {
      const { pageName, config: pageConfig, path: routePath, public: isPublic } = args as any;
      const { errors, warnings } = validatePageConfig(pageConfig);
      if (errors.length > 0) {
        let msg = `Cannot publish — fix these errors first:\n${errors.map(e => `  - ${e}`).join("\n")}`;
        if (warnings.length > 0) {
          msg += `\n\nWarnings:\n${warnings.map(w => `  - ${w}`).join("\n")}`;
        }
        return { content: [{ type: "text", text: msg }] };
      }

      // Publish the page config
      const key = `config:${config.appId}:${pageName}`;
      await kvPut(key, JSON.stringify(pageConfig));

      // Auto-add route to manifest
      const inferredPath = routePath || "/" + pageName.replace(/^pages\//, "");
      const manifestKey = `config:${config.appId}:manifest`;
      const existingManifest = await kvGet(manifestKey);

      let routeAdded = false;
      if (existingManifest) {
        const manifest = JSON.parse(existingManifest);
        const routes: any[] = manifest.load?.routes ?? manifest.routes ?? [];
        const hasRoute = routes.some((r: any) => r.path === inferredPath);

        if (!hasRoute) {
          const newRoute: Record<string, unknown> = { path: inferredPath, file: pageName };
          if (isPublic !== false) newRoute.public = true; // default public
          routes.push(newRoute);
          if (manifest.load?.routes) manifest.load.routes = routes;
          else manifest.routes = routes;
          await kvPut(manifestKey, JSON.stringify(manifest));
          routeAdded = true;
        }
      }

      const runtimeUrl = config.runtimeUrl
        ? config.runtimeUrl.replace(/clientforce-portal|[^/]+(?=\.vguruprasad91)/, config.appId)
        : null;
      const liveUrl = runtimeUrl ? `${runtimeUrl}${inferredPath}` : inferredPath;

      const warningText = warnings.length > 0
        ? `\n\nWarnings:\n${warnings.map(w => `  - ${w}`).join("\n")}`
        : "";

      return { content: [{ type: "text", text:
        `Published ${pageName} to KV (app: ${config.appId}).\n` +
        (routeAdded ? `Route added: ${inferredPath} → ${pageName} (public)\n` : `Route ${inferredPath} already exists.\n`) +
        `Live at: ${liveUrl}\n` +
        `Note: KV propagation ~60 seconds.` +
        warningText
      }] };
    }

    case "publish_manifest": {
      await kvPut(`config:${config.appId}:manifest`, JSON.stringify((args as any).manifest));
      return { content: [{ type: "text", text: `Published manifest for app "${config.appId}".` }] };
    }

    case "publish_theme": {
      await kvPut(`config:${config.appId}:theme`, JSON.stringify((args as any).theme));
      return { content: [{ type: "text", text: `Published theme for app "${config.appId}".` }] };
    }

    case "publish_datasources": {
      await kvPut(`config:${config.appId}:datasources`, JSON.stringify((args as any).datasources));
      return { content: [{ type: "text", text: `Published datasources for app "${config.appId}".` }] };
    }

    case "publish_navigation": {
      await kvPut(`config:${config.appId}:navigation`, JSON.stringify((args as any).navigation));
      return { content: [{ type: "text", text: `Published navigation for app "${config.appId}".` }] };
    }

    // ════════════════════════════════════════════════════
    // STATUS
    // ════════════════════════════════════════════════════

    case "get_app_status": {
      const runtimeUrl = config.runtimeUrl
        ? config.runtimeUrl.replace(/clientforce-portal|[^/]+(?=\.vguruprasad91)/, config.appId)
        : "Not deployed";

      const status: Record<string, unknown> = {
        activeApp: config.appId,
        runtimeUrl,
        cloudflareConnected: !!(config.accountId && config.apiToken && config.kvNamespaceId),
      };

      if (config.accountId && config.apiToken && config.kvNamespaceId) {
        const checks = ["manifest", "theme", "navigation", "datasources"];
        const results: Record<string, boolean> = {};
        for (const check of checks) {
          results[check] = (await kvGet(`config:${config.appId}:${check}`)) !== null;
        }
        const pageKeys = await kvList(`config:${config.appId}:pages/`);
        results[`pages (${pageKeys.length})`] = pageKeys.length > 0;
        status.publishedConfigs = results;

        // Show routes if manifest exists
        const manifestRaw = await kvGet(`config:${config.appId}:manifest`);
        if (manifestRaw) {
          const manifest = JSON.parse(manifestRaw);
          const routes = manifest.load?.routes ?? manifest.routes ?? [];
          status.routes = routes.map((r: any) => `${r.path} → ${r.file || r.redirect || "?"}${r.public ? " (public)" : ""}`);
        }
      }

      return { content: [{ type: "text", text: JSON.stringify(status, null, 2) }] };
    }

    case "get_ui_schema": {
      return { content: [{ type: "text", text: CATALOG_PROMPT }] };
    }

    default:
      throw new Error(`Unknown tool: ${toolName}`);
  }
});

// ─── Start ───────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(`UI Creator MCP server v2.0 running (active app: ${config.appId})`);
}

main().catch(console.error);
